# application.yml

spring:
  application:
  	name: ${APP_NAME:Logistics-server}
  datasource:
    url: jdbc:mysql://localhost:3306/express?useSSL=false&characterEncoding=utf8
    username: root
    password: tjwyzwyz5
    dirver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
  jpa:
	hibernate:
	  ddl-auto: update
	  dialect: org.hibernate.dialect.MySQL55Dialect
	  show_sql: true

server:
  port: ${APP_PORT:8080}


pebble:
  suffix:
  cache: false