# application.yml

spring:
  application:
    name: ${APP_NAME:Logistics-server}
  datasource:
    url: jdbc:mysql://localhost:3306/express?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: tjwyzwyz5
    dirver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
  jpa:
    generate-ddl: true    
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL55Dialect
        show_sql: true

server:
  port: 8443
  ssl:
    key-store: classpath:localkeystore
    key-store-password: dontpanic42
    keyStoreType: PKCS12
    keyAlias: localcert  
    key-password: dontpanic42

#keytool -storepass dontpanic42 -genkeypair -keyalg RSA -keysize 1024 -validity 3650 -alias localcert -storetype PKCS12 -keystore localkeystore -dname "CN=https://localhost:8443/"
#keytool -list -v -storetype pkcs12 -keystore localkeystore

pebble:
  suffix:
  cache: false

app:
  cors:
    mapping: /api/**
    allowedOrigins: http://localhost:3000
    allowedMethods: OPTIONS, PUT, DELETE, GET, POST, PATCH 
    allowedHeaders: "*"
    maxAge: 3600
    allowCredentials: true
    